language: node_js

# Node versions: https://node.green/
matrix:
  include:
    - os: windows
      env: CXX=g++-4.8
      node_js: "12.10.0"
    - os: linux
      env: CXX=g++-4.8
      node_js: "12.4.0"

os:
  - osx

env:
  - CXX=clang

node_js:
  - "10.9.0"
  - "10.16.3"
  - "11.0.0"
  - "11.15.0"
  - "12.0.0"
  - "12.4.0"
  - "12.10.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false
dist: precise
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-travis"
  - "test   -z $(npm -ps ls eslint  ) || npm run-script lint"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
